# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 04:09
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='datafile',
            field=models.ImageField(upload_to=api.models.image_upload_to),
        ),
    ]
