# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 24, 18, 7, 30, 810482, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
