# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_foodie_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='circle',
            name='location',
            field=models.CharField(default='test', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='test city', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='test state', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='test street', max_length=120),
            preserve_default=False,
        ),
    ]
