# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160822_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=40.7089, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='log',
            field=models.DecimalField(decimal_places=10, default=73.8154, max_digits=12),
            preserve_default=False,
        ),
    ]
