# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_circle_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='api.Foodie'),
        ),
        migrations.AddField(
            model_name='circle',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='api.Foodie'),
        ),
    ]
