# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160822_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='wouldGo',
            field=models.BooleanField(default=True),
        ),
    ]
