# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160924_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='description',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
