# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160823_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(default='test_review', max_length=80),
            preserve_default=False,
        ),
    ]
