# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_circle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to='api.Foodie'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='foodies',
            field=models.ManyToManyField(blank=True, to='api.Foodie'),
        ),
    ]
