# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_review_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='foodie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Foodie'),
            preserve_default=False,
        ),
    ]
