# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_review_foodie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodie',
            name='circles',
        ),
        migrations.DeleteModel(
            name='Circle',
        ),
    ]
