# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160924_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='foodies',
        ),
    ]
