# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160901_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 2, 1, 56, 49, 899758, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 2, 1, 56, 53, 147673, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
