# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160924_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleMemebership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Circle')),
                ('foodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Foodie')),
            ],
        ),
    ]
