# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_circlememebership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CircleMemebership',
            new_name='CircleMembership',
        ),
    ]
