# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 03:30
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160924_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.ImageField(upload_to=api.models.circle_image_upload_to)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Circle')),
            ],
        ),
    ]
