# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_poll_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='Restaurant',
            new_name='Restaurants',
        ),
    ]
