# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160902_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(default='Test Poll', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='Test Poll 2', max_length=80),
            preserve_default=False,
        ),
    ]
